### ISSUE TITLE
Improve library API

### ISSUE THREAD

**Issue by dx3mod** [romanchechyotkin/nats.ocaml#1]
Some suggestions for improving library's API. 

## Labeled functions 

```ocaml
(* now *)
Client.connect host port
(* with labeled arguments *)
Client.connect ~host ~port ()
```
You can also set defaults for them 
```ocaml
(* now *)
let connect host port = ...
(* with defaults *)
let connect ?(host = default_host) ?(port = default_port) () = ...
```

### or use modules 

```ocaml
let conn = Client.connect (module struct 
  let host = ..
  let port = ...
 end)
```

## with_connect

Automatically close a resource 

```ocaml
(* now *) 
let conn = Client.connect ()
...
Client.close conn

(* with with_connect *)
Client.with_connect ... @@ fun conn -> 
  ...
```

### first-class modules  or objects for connection 

```ocaml
(* object *)
Client.with_connect ~host ~port (fun conn -> 
  conn#pub "FOO")

(* first-class module *)
Client.with_connect ~host ~port (fun (module Conn) -> 
  Conn.pub "FOO")
```

## signature for abstraction 

```ocaml
(* now *)
type 'a t = { sockaddr : sockaddr; socket : Lwt_unix.file_descr }
(* should be *)
type 'a t
```

Module signatures hide internal implementation.

## unsafe 

In some cases you can use unsafe functions ([read this](https://ocamlportal.ru/recipes/unsafe.html))

```ocaml
(* now *)
let msg : bytes = Bytes.of_string message 
(* better performance *)  
let msg  = Bytes.unsafe_of_string message 
```

## print_endline

:cactus: 

## monadic syntax 

Prefer monadic syntax `let*`, `let+`, or `ppx_lwt`.

**Comment by romanchechyotkin** [comment]
Tnaks a lot, but question ,can i use labeled args with optional together?
![image](https://github.com/user-attachments/assets/12f2f173-da6c-46a7-952d-f8c9532d3787)
Ocaml does not allow me to do that
@dx3mod

**Comment by romanchechyotkin** [comment]
So i found the answer, unit type at the end is the necessary thing
![image](https://github.com/user-attachments/assets/4c1f196a-8cbd-48eb-bb03-4fefea7988b7)
and now i have these things
![image](https://github.com/user-attachments/assets/7319ea6c-c329-4664-9b56-1b8f0cfc4983)

**Comment by dx3mod** [comment]
Yes, otherwise OCaml won't know where to stop.

**Comment by dx3mod** [comment]
@romanchechyotkin, you may make a payload argument for sub/pub functions positional, which makes partial application more comfortable. 

```ocaml
let notify  = Client.pub ~client ~subject:"NOTIFY" 
(* val notify : payload -> unit Lwt.t *)

value 
|> do_something_a
|> do_something_b
|> notify
```
