### ISSUE TITLE
Subscription routing

### ISSUE THREAD

**Issue by dx3mod** [romanchechyotkin/nats.ocaml#15]
Filter incoming messages and route them to subscribers.

-  ~~Subject parser~~
- [ ] Reply to
- [x] Routing

**Comment by dx3mod** [comment]
I'll do it this week.

**Comment by dx3mod** [comment]
Checking a SID was enough to route incoming messages. But there is also a "reply to" mechanism. I don't understand it yet.

**Comment by dx3mod** [comment]
My #20 has been moved to #22 PR

**Comment by romanchechyotkin** [comment]
about Reply-to mechanism
i think this is NATS feature, u just need to provide two subjects

**Comment by romanchechyotkin** [comment]
and NATS is going to manage rounting messages into specific subjects, we just need to handle incoming messages

**Comment by dx3mod** [comment]
Okay. :ok_hand:
