### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by dx3mod** [romanchechyotkin/nats.ocaml#28]
Right now, the library mostly uses exceptions, and that seems to be good enough. Should we use monadic error handling (option, result types) or stay with exceptions?

**Comment by romanchechyotkin** [comment]
I guess, now we need to implement logic and get some MVP library
and then think about refactoring

**Comment by dx3mod** [comment]
Это верно, но нет ничего более постоянного, чем временное 😊
