### ISSUE TITLE
Add labels for issues

### ISSUE THREAD

**Issue by dx3mod** [romanchechyotkin/nats.ocaml#32]
I don't have permission to do that.

**Comment by romanchechyotkin** [comment]
what issues labels do you want to see

**Comment by dx3mod** [comment]
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by romanchechyotkin** [comment]
sent you invite to collaborate in repo

**Comment by dx3mod** [comment]
Okay
