### ISSUE TITLE
Design Subscriptions 

### ISSUE THREAD

**Issue by dx3mod** [romanchechyotkin/nats.ocaml#8]
A subscription system needs to be designed. How it should look like and how it should work. 

Ideas that come to mind
- Callbacks. But how to make it work in the background? And that requires a mutable state
  ```ocaml
   client#sub ~subject"FOO.*" (fun event -> ...)
   ```
- Blocking listener (bad idea) something like
  ```ocaml
   client#listen (fun any_event -> ...)
   ```

A real-world example would be nice. And a list of tasks that need to be covered.

**Comment by romanchechyotkin** [comment]
I thought about callbacks, in this way subscriptions designed in Golang client, for this we need to listen incoming MSG requests from server https://docs.nats.io/reference/reference-protocols/nats-protocol#msg

**Comment by romanchechyotkin** [comment]
thats why i asked you about Lwt.async listener which handles all incoming messages (OK+, PING, ERR-, MSG)

**Comment by romanchechyotkin** [comment]
Golang client reference https://github.com/nats-io/nats.go?tab=readme-ov-file#basic-usage

**Comment by dx3mod** [comment]
I want a more idiomatic FP solution. :eyes:

**Comment by romanchechyotkin** [comment]
i guess its like List.iter ~f: (our callback for incoming subject messages)

**Comment by romanchechyotkin** [comment]
but we need to think about how to listen for messages of specific suibject and provide them to needed callback

**Comment by dx3mod** [comment]
This can be solved with FRP (Functional Reactive Programming), but I'm not sure how to do it. See [react](https://erratique.ch/software/react/doc/React/index.html) and [Функциональное реактивное программирование — Антон Холомьёв](https://www.youtube.com/watch?v=QOLM4EyJNsc) (in rus).

**Comment by romanchechyotkin** [comment]
appreciate

**Comment by dx3mod** [comment]
I'm currently experimenting with callback.  I hope to have a PR ready soon.

**Comment by romanchechyotkin** [comment]
Appreciate, i am busy now with tech interviews and cant find time to work on lib

**Comment by dx3mod** [comment]
In the end, I found a design solution. Lwt has the `Lwt_stream` abstraction for async lazy collections. Together with `Lwt.async` we got the right result.

Raw demo:
```ocaml
let%lwt foo_subj = client#sub ~subject:"FOO" () in

Lwt.async (fun () ->
  Lwt_stream.iter 
    (printf "from foo: %s")
    foo_subj );

client#pub ~subject:"FOO" "Hi!";%lwt
```

With some simple wrapper:
```ocaml
Sub.handle foo_subj (printf "from foo %s")
```

In the next PR I plan to cover the basics of subscription mechanics and incoming messages. And do a little reorganization of the project again.
